-- AlterTable
ALTER TABLE "dailyGoals" ALTER COLUMN "inTakeGoal" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "burnGoal" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "weight" ALTER COLUMN "weight" SET DATA TYPE DOUBLE PRECISION;
