-- AlterTable
ALTER TABLE "dailyGoals" ADD COLUMN     "burnGoalCount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "inTakeGoalCount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "waterCount" INTEGER NOT NULL DEFAULT 0;
